"""initial

Revision ID: f3e3e80d8aed
Revises: 
Create Date: 2024-01-03 17:44:10.866116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e3e80d8aed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Enum(), nullable=False),
    sa.Column('discount', sa.Enum(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promocodes')
    # ### end Alembic commands ###
