"""initial

Revision ID: c56abd5cb589
Revises: 
Create Date: 2024-01-03 17:27:08.678996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56abd5cb589'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'IN_PROCESS', 'DONE', 'CANCELED', name='deliverystatuses'), nullable=False),
    sa.Column('type', sa.Enum('PICKUP', 'DELIVERY', name='deliverytypes'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    # ### end Alembic commands ###
